repos:
-   repo: local
    hooks:
    - id: requirements
      name: requirements
      entry: bash -c 'venv/bin/pip freeze | sort > requirements.txt; git add requirements.txt'
      language: system
      pass_filenames: false
      stages: [commit]